name: "Deploy Infra - SPA"
description: "Deploy Single Page Application Infrastructure."
inputs:
  name:
    description: "Name of the SPA."
    required: true
  domainName:
    description: "Domain Name that will direct to this project."
    required: true
  certificateArn:
    description: "Certification ARN associated with this domain name and '*.{domainName}'."
    required: true
outputs:
  bucketArn:
    description: "Bucket Arn to deploy the SPA on."
runs:
  using: docker
  image: docker://ghcr.io/danmaklenorg/deploy-infra-spa:latest
  args:
    - ${{inputs.name}}
    - ${{inputs.domainName}}
    - ${{inputs.certificateArn}}
