name: "Deploy Infra - SPA"
description: "Deploy Single Page Application Infrastructure."
inputs:
  name:
    description: "Name of the SPA."
    required: true
  domainName:
    description: "Domain Name that will direct to this project."
    required: true
  certificateArn:
    description: "Certification ARN associated with this domain name and '*.{domainName}'."
    required: true
  awsAccessKeyId:
    description: "AWS Access Key Id"
    required: true
  awsSecretAccessKey:
    description: "AWS Secret Access Key"
    required: true
  awsRegion:
    description: "AWS Region"
    required: true
outputs:
  bucketName:
    description: "Bucket Arn to deploy the SPA on."
runs:
  using: docker
  image: Dockerfile
  env:
    AWS_ACCESS_KEY_ID: ${{ inputs.awsAccessKeyId }}
    AWS_SECRET_ACCESS_KEY: ${{ inputs.awsSecretAccessKey }}
    AWS_DEFAULT_REGION: ${{ inputs.awsRegion }}
  args:
    - ${{inputs.name}}
    - ${{inputs.domainName}}
    - ${{inputs.certificateArn}}
