FROM mcr.microsoft.com/dotnet/sdk:6.0

COPY ../../../Infra.SinglePageApplicationWebsite/bin/Release/net6.0/Constructs.dll .
COPY ../../../Infra.SinglePageApplicationWebsite/bin/Release/net6.0/Amazon.CDK.Lib.dll .
COPY ../../../Infra.SinglePageApplicationWebsite/bin/Release/net6.0/Infra.SinglePageApplicationWebsite .
COPY entrypoint.sh .
